[phases.setup]
commands = [
  "composer install --no-dev --optimize-autoloader",
  "php artisan key:generate",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "mkdir -p /var/log/php-fpm",  # Create the log directory
  "touch /var/log/php-fpm/error.log"  # Create the error log file
]

[phases.start]
commands = [
  "php-fpm --fpm-config ./php-fpm.conf"
]

[services.nginx]
config = '''
server {
    listen 80;
    server_name _;

    root /app/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME /app/public$fastcgi_script_name;
    }
}
'''
